name = "markdown-nice"
main = "worker/index.js"
compatibility_date = "2024-06-01"
workers_dev = false

# TODO: set your Cloudflare account id
# account_id = "YOUR_ACCOUNT_ID"

routes = [
  { pattern = "mdnice.disign.me/*", zone_name = "disign.me" }
]

assets = { directory = "./docs", binding = "ASSETS" }
